### ISSUE TITLE
Kind request to deprecate package / delete GitHub repo

### ISSUE THREAD

**Issue by dandv** [denysonique/Meteor-jade-handlebars#3]
This package is 2+ years old and probably no longer works with Meteor 1.0+.

You can hide it from Atmosphere searches while letting dependent packages and apps use it with the following command:

```
meteor admin set-unmigrated <package:name>
```

To remove `mrt` as a contributor:
    meteor admin maintainers yourusername:your-package --remove mrt

If you were originally the maintainer on the old package system, you can attach your Meteor Developer account at http://atmosphere.meteor.com/accounts, then ping @tmeasday to give you ownership of the old package.

**Comment by denysonique** [comment]
@dandv  @tmeasday feel free to remove this package from Atmosphere.

**Comment by hipertracker** [comment]
@denysonique  The package can be removed by non-owner.
